apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-pod-namespace
  labels:
    app: my-label
spec:
  containers:
    - name: my-pod-container
      image: nginx:1.14.2
      ports:
        - containerPort: 80
